import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
async function main() {
  const db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$ select (nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'sub')::uuid $$;
    grant usage on schema public,auth to anon,authenticated,service_role;
    grant execute on function auth.uid() to public;
    alter default privileges in schema public grant all on tables to authenticated,service_role;
    alter default privileges in schema public grant all on sequences to authenticated,service_role;
  `);
  const schema = ['schema.sql','v2-schema.sql','v3-company-os-schema.sql','v5-daily-brief-schema.sql','v6-next-best-action.sql'];
  for (const file of schema) await db.exec(fs.readFileSync(path.join('supabase',file),'utf8'));
  for (const file of fs.readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort()) await db.exec(fs.readFileSync(path.join('supabase/migrations',file),'utf8'));
  const owner='00000000-0000-4000-8000-000000000001', other='00000000-0000-4000-8000-000000000002', company='00000000-0000-4000-8000-000000000010';
  await db.exec(`insert into auth.users values ('${owner}'),('${other}'); insert into companies(id,user_id,name) values('${company}','${owner}','Test company');`);
  // Existing V3 approval, automation, event bridge and tenant tests remain intact.
  await db.exec(fs.readFileSync('tests/v3-security.sql','utf8'));
  console.log('PASS existing V3 SQL regression suite');
  const call=async(key,op,data={})=>(await db.query('select agent_workflow($1,$2,$3,$4,$5::jsonb) result',[company,owner,key,op,JSON.stringify(data)])).rows[0].result;
  const key='00000000-0000-4000-8000-000000000020';
  const plan={goal:'Research competitors and prepare a launch strategy',steps:[{agentId:'research',objective:'Research competitors',actionType:'analyze_context',dependsOn:[]},{agentId:'marketing',objective:'Prepare launch strategy',actionType:'analyze_context',dependsOn:[0]}]};
  await db.exec('set role service_role');
  let runs=await call(key,'start',plan); assert.equal(runs.length,2);
  const replay=await call(key,'start',plan); assert.equal(replay[0].id,runs[0].id);
  await assert.rejects(call(key,'start',{...plan,goal:'Different goal'}));
  await assert.rejects(call(key,'claim',{runId:runs[1].id}));
  assert.ok(await call(key,'claim',{runId:runs[0].id}));
  assert.equal(await call(key,'claim',{runId:runs[0].id}),null);
  const output={summary:'Saved evidence analysis, not live research.',findings:[],drafts:['Draft launch copy'],unknowns:['No competitor sources'],actions:[{actionType:'create_task',parameters:{title:'Validate positioning',description:'Interview customers'},reason:'Evidence needed'}]};
  runs=await call(key,'finish',{runId:runs[0].id,output,usage:{modelCalls:1}});
  assert.equal(runs[0].status,'waiting_approval');
  assert.ok(await call(key,'claim',{runId:runs[1].id}));
  runs=await call(key,'finish',{runId:runs[1].id,output:{...output,actions:[]},usage:{modelCalls:1}});
  assert.equal(runs[1].status,'completed');
  await assert.rejects(call(key,'finish',{runId:runs[1].id,output,usage:{}}));
  const action=(await db.query("select * from ai_actions where agent_run_id=$1 and action_type='create_task'",[runs[0].id])).rows[0];
  await db.exec(`set role authenticated; select set_config('request.jwt.claims','{"sub":"${owner}","role":"authenticated"}',false)`);
  await assert.rejects(db.query("update ai_actions set permission_level='AUTO' where id=$1",[action.id]));
  await assert.rejects(db.query("update ai_actions set agent_id='coding' where id=$1",[action.id]));
  await assert.rejects(db.query('delete from ai_actions where id=$1',[action.id]));
  await assert.rejects(db.query("insert into agent_runs(company_id) values($1)",[company]));
  await assert.rejects(call(key,'claim',{runId:runs[0].id}));
  await assert.rejects(db.query('select execute_internal_action_v2($1,true)',[action.id]));
  await assert.rejects(db.query('select execute_internal_action($1,false)',[action.id]));
  await db.query("update ai_actions set title='Edited task' where id=$1",[action.id]);
  const approved=(await db.query('select execute_internal_action($1,true) result',[action.id])).rows[0].result;
  assert.ok(approved.record_id);
  const again=(await db.query('select execute_internal_action($1,true) result',[action.id])).rows[0].result;
  assert.deepEqual(again,approved);
  assert.equal((await db.query('select status from agent_runs where id=$1',[runs[0].id])).rows[0].status,'completed');
  await assert.rejects(db.query("update memories set content='forged' where source_run_id=$1",[runs[0].id]));
  await assert.rejects(db.query("delete from activity_events where agent_run_id=$1",[runs[0].id]));
  await db.exec(`select set_config('request.jwt.claims','{"sub":"${other}","role":"authenticated"}',false)`);
  for (const table of ['agent_runs','ai_actions','memories','activity_events']) assert.equal((await db.query('select * from '+table+' where company_id=$1',[company])).rows.length,0);
  await assert.rejects(db.query('select execute_internal_action($1,true)',[action.id]));
  console.log('PASS workflow dependencies, replay protection, approvals, provenance and tenant isolation');
  await db.exec('set role service_role');
  const key2='00000000-0000-4000-8000-000000000021';
  const failed=await call(key2,'start',{goal:'Coding analysis',steps:[{agentId:'coding',objective:'Analyze issues',actionType:'analyze_github_issues',dependsOn:[]}]});
  await call(key2,'claim',{runId:failed[0].id});
  const stopped=await call(key2,'fail',{error:'No saved GitHub issues are available.'});
  assert.equal(stopped[0].status,'failed');
  assert.equal((await db.query('select count(*)::int n from memories where source_run_id=$1',[failed[0].id])).rows[0].n,0);
  console.log('PASS failure persistence without invented output');
  const key3='00000000-0000-4000-8000-000000000022';
  let invalid=await call(key3,'start',{goal:'Research market',steps:[{agentId:'research',objective:'Research market',actionType:'analyze_context',dependsOn:[]}]});
  await call(key3,'claim',{runId:invalid[0].id});
  await assert.rejects(call(key3,'finish',{runId:invalid[0].id,output:{...output,actions:[{...output.actions[0],actionType:'gmail.send_email'}]},usage:{}}));
  assert.equal((await db.query('select count(*)::int n from memories where source_run_id=$1',[invalid[0].id])).rows[0].n,0);
  assert.equal((await db.query('select status from ai_actions where agent_run_id=$1',[invalid[0].id])).rows[0].status,'executing');
  invalid=await call(key3,'finish',{runId:invalid[0].id,output,usage:{modelCalls:1}});
  const rejectId=(await db.query("select id from ai_actions where agent_run_id=$1 and action_type='create_task'",[invalid[0].id])).rows[0].id;
  await db.exec(`set role authenticated; select set_config('request.jwt.claims','{"sub":"${owner}","role":"authenticated"}',false)`);
  await db.query("update ai_actions set status='cancelled' where id=$1",[rejectId]);
  assert.equal((await db.query('select status from agent_runs where id=$1',[invalid[0].id])).rows[0].status,'cancelled');
  await assert.rejects(db.query('select execute_internal_action($1,true)',[rejectId]));
  await db.exec('set role service_role');
  const key4='00000000-0000-4000-8000-000000000023';
  const stale=await call(key4,'start',plan);
  await call(key4,'claim',{runId:stale[0].id});
  await db.query("update agent_runs set created_at=now()-interval '5 minutes' where request_key=$1",[key4]);
  const recovered=await call(key4,'recover');
  assert.deepEqual(recovered.map(r=>r.status),['failed','cancelled']);
  const secondCompany='00000000-0000-4000-8000-000000000011';
  await db.query("insert into companies(id,user_id,name) values($1,$2,'Other workspace')",[secondCompany,owner]);
  await assert.rejects(db.query("insert into memories(company_id,user_id,kind,title,content,source_run_id) values($1,$2,'learning','Invalid','Invalid',$3)",[secondCompany,owner,runs[0].id]));
  console.log('PASS atomic rollback, rejected approvals, stale-run recovery and cross-company foreign keys');
  await db.close();
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});

