import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient, hasSupabaseConfig } from "../../../lib/supabase/server";

type ReportContent = { summary?: string; problem?: string; gap?: string; mvp?: string[]; avoid?: string[]; sources?: string[] };
type StoredReport = { title: string; verdict: string; score: number; report: ReportContent; created_at: string };
const demo: StoredReport = { title: "Local service growth copilot", verdict: "TEST FIRST", score: 74, created_at: new Date().toISOString(), report: { summary: "A focused growth assistant for independent home-service businesses has a credible wedge: owners need more predictable enquiries but lack the time and specialist support to run marketing systems.", problem: "Owners lose leads because follow-up, review collection and local visibility are inconsistent.", gap: "Existing tools are broad marketing suites or disconnected AI writers.", mvp: ["Weekly growth plan built from a business profile", "Lead follow-up sequences for email and SMS", "Review request and local-content generator", "A simple results dashboard"], avoid: ["Broad platform features", "Premature automation"], sources: ["Google Business Profile documentation", "Founder interviews required"] } };

export default async function Report({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  let report: StoredReport | null = id === "demo" ? demo : null;
  if (!report && hasSupabaseConfig()) {
    const supabase = await createClient();
    const { data: claims } = await supabase.auth.getClaims();
    if (claims?.claims?.sub) { const { data } = await supabase.from("reports").select("title,verdict,score,report,created_at").eq("id", id).maybeSingle(); report = data as StoredReport | null; }
  }
  if (!report) notFound();
  const content = report.report;
  const verdictLine = report.verdict === "BUILD" ? "A strong opportunity, with a clear reason to pursue the next validation step." : report.verdict === "AVOID" ? "The current risks outweigh the likely opportunity." : "Promising direction, but earn the right to build through customer evidence.";
  return <main className="app-shell"><header className="app-nav"><Link className="brand" href="/"><span className="brand-mark">✦</span> AI Co-Founder</Link><div><Link href="/reports">My reports</Link><Link href="/new">New idea</Link></div></header><section className="report"><div className="report-top"><div><Link className="back" href="/reports">← All reports</Link><div className="eyebrow"><span></span> CO-FOUNDER VERDICT</div><h1>{report.title}</h1><p>Analysis generated {new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(report.created_at))} · Decision brief</p></div><button className="export">Export report ↗</button></div><div className="verdict-row"><div className="score"><small>BUSINESS SCORE</small><strong>{report.score}</strong><span>/100</span></div><div className="verdict"><small>RECOMMENDATION</small><h2><i></i>{report.verdict}</h2><p>{verdictLine}</p></div><div className="confidence"><small>CONFIDENCE</small><b>Directional</b><p>Based on early research and stated assumptions.</p></div></div><div className="report-grid"><div className="report-main"><ReportBlock tag="EXECUTIVE SUMMARY" title="The clearest path forward." text={content.summary}/><div className="two"><ReportBlock tag="CUSTOMER PROBLEM" title="A job that won’t wait." text={content.problem}/><ReportBlock tag="COMPETITIVE GAP" title="Win by being specific." text={content.gap}/></div><ReportBlock tag="RECOMMENDED MVP" title="Build the smallest proof engine." list={content.mvp}/><ReportBlock tag="AVOID FOR NOW" title="Keep the first version sharp." list={content.avoid}/></div><aside><div className="side-card"><span>YOUR NEXT MOVE</span><h3>Talk to 10 customers this week.</h3><p>Ask about their current workaround, what it costs them, and what would make them switch.</p><button>Open 7-day plan →</button></div><div className="source-card"><span>RESEARCH TRACE</span><p><i className="verified"></i> Verified information</p><p><i className="estimate"></i> AI estimates</p><p><i className="assume"></i> Assumptions</p><hr/>{(content.sources ?? []).map(source => <small key={source}>↗ {source}</small>)}</div></aside></div></section></main>;
}
function ReportBlock({ tag, title, text, list }: { tag: string; title: string; text?: string; list?: string[] }) { return <article className="block"><span>{tag}</span><h2>{title}</h2>{text && <p>{text}</p>}{list && <ul>{list.map(item => <li key={item}><b>✓</b>{item}</li>)}</ul>}<small className="data-tag">AI ESTIMATE</small></article>; }
