"use client";
import { FormEvent, useState } from "react";
import { createClient } from "../../lib/supabase/client";

export default function AuthPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setMessage(""); try { const supabase = createClient(); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) { const signup = await supabase.auth.signUp({ email, password, options: { emailRedirectTo: `${window.location.origin}/auth/callback` } }); setMessage(signup.error ? signup.error.message : "Check your email to confirm your account, then sign in."); } else window.location.assign("/reports"); } catch { setMessage("Add your Supabase URL and publishable key to .env.local first."); } finally { setLoading(false); } }
  async function signInWithGoogle() { setLoading(true); setMessage(""); try { const supabase = createClient(); const { error } = await supabase.auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${window.location.origin}/auth/callback` } }); if (error) setMessage(error.message); } catch { setMessage("Google sign-in needs your Supabase settings first."); } finally { setLoading(false); } }
  return <main className="auth-page"><a className="brand" href="/"><span className="brand-mark">✦</span> AI Co-Founder</a><section className="auth-card"><div className="eyebrow"><span></span> YOUR PRIVATE CO-FOUNDER ROOM</div><h1>Save the thinking<br/>that matters.</h1><p>Sign in to keep your research and decision briefs private to you.</p><button className="google-button" type="button" onClick={signInWithGoogle} disabled={loading}><span aria-hidden="true">G</span> Continue with Google</button><div className="auth-divider"><span>or use email</span></div><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required placeholder="you@example.com"/></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required minLength={8} placeholder="At least 8 characters"/></label><button className="primary-action" disabled={loading}>{loading ? "Working…" : "Continue with email →"}</button></form>{message && <small className="auth-message">{message}</small>}<small>New here? We’ll create your account securely.</small></section></main>;
}
