import Link from 'next/link';
import type { IntelligenceData } from '../lib/intelligence/data';
import { executionScore } from '../lib/intelligence/data';
import { PROVIDERS } from '../lib/connectors/base';
import { V3Button } from './v3-controls';
import StartTaskButton from './start-task-button';
import type { DailyBrief } from '../lib/daily-brief';

export type DashboardProps={companyId:string;name:string;displayName:string;data:IntelligenceData;missions:{id:string;objective:string;progress:number}[];tasks:{id:string;title:string;status:string;priority:string}[];goal:{title:string;progress:number}|null;brief:DailyBrief|null;demo?:boolean};
function Bar({value,tone='purple'}:{value:number;tone?:string}) {return <div className={`v3-track ${tone}`}><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>;}
export default function V3Dashboard({companyId,name,displayName,data,missions,tasks,goal,brief,demo=false}:DashboardProps) {
  const href=(s:string)=>demo?`/demo/v3?section=${s}`:`/company/${companyId}/${s}`;
  const github=data.connections.find(c=>c.provider==='github'&&c.status==='connected');
  const issues=typeof github?.metadata?.open_issues==='number'?github.metadata.open_issues:null;
  const metrics=[{name:'Revenue',value:demo?'₹2.45L':'—',hint:demo?'↑ 18% · demo':'Connect billing data',icon:'◈',tone:'cyan'}, {name:'Website users',value:demo?'12,430':'—',hint:demo?'↑ 32% · demo':'Connect analytics',icon:'▣',tone:'blue'}, {name:'Signup conversion',value:demo?'18.6%':'—',hint:demo?'↓ 12% · demo':'Connect funnel data',icon:'◎',tone:'pink'}, {name:'Active customers',value:demo?'8':'—',hint:demo?'↑ 2 · demo':'Connect billing data',icon:'♧',tone:'green'}, {name:'Open issues',value:demo?'3':issues??'—',hint:demo?'↓ 5 · demo':github?'GitHub snapshot':'Connect GitHub',icon:'⑂',tone:'purple'}];
  const execution=executionScore(tasks);
  const scores=demo?[85,72,64,71,82]:[null,null,null,null,execution];
  const insight=data.insights.find(i=>!['resolved','dismissed'].includes(i.status??''));
  const ranks:Record<string,number>={critical:0,high:1,medium:2,low:3};
  const priorities=tasks.filter(t=>t.status!=='completed').sort((a,b)=>(ranks[a.priority]??4)-(ranks[b.priority]??4)).slice(0,5);
  return <section className="v3-dashboard">
    <div className="v3-page-heading"><div><h1>Welcome back{displayName?`, ${displayName}`:''}! <span aria-hidden="true">☀️</span></h1><p>Your company, in focus. Here’s what’s happening with {name}.</p></div><span className="v3-badge">{demo?'DEMO DATA':'Latest available data'}</span></div>
    {demo&&<div className="v3-demo-banner">Presentation demo · All metrics and activity below are simulated. No external accounts are connected.</div>}
    {data.unavailable&&<p className="v3-error" role="alert">Some V3 data could not be loaded. Existing workspace tools remain available.</p>}
    <div className="v3-metrics">{metrics.map((m,i)=><article className={`v3-card v3-metric ${m.tone}`} key={m.name}><div><span className="v3-metric-icon">{m.icon}</span><small>{m.name}</small></div><strong>{m.value}</strong><small>{m.hint}</small>{demo?<svg viewBox="0 0 160 24" aria-hidden="true"><path d={['M0 20L15 21L25 18L38 20L50 20L62 21L75 17L86 20L99 19L115 14L126 17L141 12L160 10','M0 22L15 19L30 11L45 6L60 13L75 17L90 9L105 13L120 6L135 12L160 9','M0 13L15 16L30 8L45 7L60 15L75 18L90 14L105 21L120 19L135 23L160 22'][i%3]} fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>:<div className="v3-metric-rule"/>}</article>)}</div>
    <div className="v3-dashboard-grid">
      <article className="v3-card v3-pulse"><div className="v3-card-heading"><h2><span className="v3-accent">◧</span> Company Pulse</h2><span className="v3-badge">{demo?'Demo':'Evidence first'}</span></div><p>Available signals, without invented precision.</p><div className="v3-pulse-body"><div className={`v3-ring ${demo?'is-demo':''}`}><div><strong>{demo?'78':'—'}</strong><small>{demo?'/ 100':'Insufficient data'}</small></div></div><div className="v3-scores">{['Product','Market validation','Growth','Revenue','Execution'].map((s,i)=><div className="v3-score" key={s}><span>{s}</span><Bar value={scores[i]??0} tone={i===4?'green':i===2?'yellow':'cyan'}/><b>{scores[i]??'—'}</b></div>)}</div></div><small>{demo?'Simulated score for presentation.':'Execution = completed / all tasks. Overall health needs verified business outcomes.'}</small></article>
      <article className="v3-card v3-insight"><div className="v3-card-heading"><h2><span className="v3-ai-icon">AI</span> Insight to review</h2><Link href={href('insights')}>View all →</Link></div><h3>{insight?.title??'Your next insight starts with evidence'}</h3><p>{insight?.description??'Connect GitHub and refresh intelligence to review company signals. You will only see warnings supported by recorded data.'}</p><div className="v3-button-row">{insight?<><Link className="v3-button v3-primary" href={href('insights')}>Review insight</Link><Link className="v3-button" href={href('investigations')}>See investigations</Link></>:<><Link className="v3-button v3-primary" href={href('connections')}>Connect a tool</Link><V3Button companyId={companyId} op="refresh" demo={demo}>Refresh intelligence</V3Button></>}</div></article>
      <article className="v3-card"><div className="v3-card-heading"><h2>Active Missions</h2><Link href={demo?'/demo/v3?section=insights':href('mission')}>View all →</Link></div>{missions.length?missions.slice(0,3).map((m,i)=><div className="v3-mission" key={m.id}><span className={`v3-number tone-${i}`}>{i+1}</span><div><b>{m.objective}</b><Bar value={m.progress} tone={i===0?'green':i===2?'blue':'purple'}/><small>Linked task completion</small></div><strong>{m.progress}%</strong></div>):<p>No active missions yet. Your existing mission planner is ready when you are.</p>}</article>
      <article className="v3-card"><div className="v3-card-heading"><h2>Today’s Priorities</h2><Link href={demo?'/demo/v3?section=approvals':href('tasks')}>See all tasks →</Link></div>{priorities.length?priorities.map(t=><div className="v3-task-row" key={t.id}><span className={`v3-priority ${t.priority}`} aria-label={t.priority}>●</span><span>{t.title}</span>{demo?<Link className="v3-button" href={href('approvals')}>Review demo action</Link>:<StartTaskButton taskId={t.id}/>}</div>):<p>No open tasks. Set your next objective from Quick Actions.</p>}<small>Starting a task changes its status; it does not execute development work.</small></article>
      <article className="v3-card"><div className="v3-card-heading"><h2>Connected Tools</h2><Link href={href('connections')}>Manage →</Link></div><div className="v3-tools">{PROVIDERS.map(p=>{const c=data.connections.find(c=>c.provider===p.id);return <Link href={href('connections')} className="v3-tool" key={p.id}><span className={`v3-tool-icon ${p.id}`}>{p.icon}</span><b>{p.name}</b><small className={c?.status==='connected'?'v3-green':''}>{demo?'Demo data':c?.status??'Needs setup'}</small></Link>})}</div></article>
      <article className="v3-card" id="activity"><div className="v3-card-heading"><h2>Recent Activity</h2><Link href={href('events')}>View all →</Link></div>{data.events.length?data.events.slice(0,4).map(e=><div className="v3-event" key={e.id}><span className="v3-event-dot">✓</span><div><b>{e.title}</b><small>{demo?'Demo event':e.source} · {(e.occurred_at??e.created_at).slice(0,10)}</small></div></div>):<p>No connected events yet. Your V2 activity remains in the <Link href={href('overview')+'#activity'}>workspace overview</Link>.</p>}</article>
      <article className="v3-card" id="daily-brief"><div className="v3-card-heading"><h2>Daily Brief & Next Best Action</h2><V3Button companyId={companyId} op="refresh" demo={demo}>Refresh</V3Button></div><div id="next-action"><h3>{brief?.nextBestAction.title??'Start with one measurable objective'}</h3><p>{brief?.nextBestAction.reason??'Connect a tool or choose a mission to give your company a clear next step.'}</p>{brief?.nextBestAction.taskId&&!demo&&<StartTaskButton taskId={brief.nextBestAction.taskId}/>}</div><Link href={href('approvals')}>Prepare an internal action →</Link></article>
      <article className="v3-card" id="primary-goal"><div className="v3-card-heading"><h2>Moving towards your vision</h2><Link href={demo?'/demo/v3?section=approvals':href('overview')}>Workspace overview →</Link></div><h3>{goal?.title??'No primary goal yet'}</h3><Bar value={goal?.progress??0}/><p>{goal?.progress??0}% of linked tasks complete · Validate business outcomes separately.</p></article>
    </div>
    <footer className="v3-footer">AI Co-Founder <span>From idea to impact. Together.</span><span>v3 · Connected intelligence</span></footer>
  </section>;
}
