'use client';
import Link from 'next/link';
import { useState } from 'react';
import { PROVIDERS } from '../lib/connectors/base';
import { CONNECTORS, connectorStatus } from '../lib/connectors/registry';
import { AGENTS, isAgentId } from '../lib/agents/registry';
import { evidenceText, type IntelligenceData, type V3Record } from '../lib/intelligence/data';
import { useIntelligence } from './v3-controls';
import GitHubConnection from './github-connection';

const TITLES:Record<string,string>={connections:'Connections',insights:'Insights',investigations:'Investigations',approvals:'Approval center',automations:'Automations',executions:'Execution history',events:'Company events'};
export default function V3Module({companyId,section,data,demo=false}:{companyId:string;section:string;data:IntelligenceData;demo?:boolean}) {
  const {run,busy,message,failed}=useIntelligence(companyId,demo);
  const [repository,setRepository]=useState(''),[edit,setEdit]=useState<V3Record|null>(null),[title,setTitle]=useState(''),[description,setDescription]=useState('');
  const [actionType,setActionType]=useState('create_task'),[requestKey,setRequestKey]=useState('');
  const [filePath,setFilePath]=useState('README.md'),[fileContent,setFileContent]=useState('');
  const [showResolved,setShowResolved]=useState(false);
  const href=(s:string)=>demo?`/demo/v3?section=${s}`:`/company/${companyId}/${s}`;
  const records=section==='insights'?(showResolved?data.insights:data.insights.filter(i=>!['resolved','dismissed'].includes(i.status??''))):section==='investigations'?data.investigations:section==='executions'?data.actions:section==='events'?data.events:data.actions.filter(a=>a.status==='awaiting_approval');
  const automation=data.automations[0];
  return <section className="v3-module">
    <div className="v3-page-heading"><div><span className="v3-eyebrow">CONNECTED COMPANY INTELLIGENCE</span><h1>{TITLES[section]}</h1><p>{demo?'Demo data · no live accounts or external execution.':'Your company’s signals, evidence and approved work.'}</p></div><Link className="v3-button" href={demo?'/demo/v3':`/company/${companyId}`}>← Dashboard</Link></div>
    {data.unavailable&&<p role="alert" className="v3-error">Some intelligence records could not be loaded. Refresh before acting.</p>}
    {message&&<p className={failed?'v3-error':'v3-notice'} role={failed?'alert':'status'}>{message}</p>}
    {section==='connections'?<>
      <div className="v3-provider-grid">{PROVIDERS.map(p=>{const c=data.connections.find(c=>c.provider===p.id);return <article className="v3-card" key={p.id}><span className={`v3-tool-icon ${p.id}`}>{p.icon}</span><h2>{p.name}</h2><span className="v3-badge">{demo?'Demo data':connectorStatus(p.id,c)}</span><p>{p.description}</p>{c&&<><p>{String(c.metadata?.account??c.metadata?.repository??'')}</p><small>Last successful sync: {c.last_sync_at?new Date(c.last_sync_at).toLocaleString('en-GB',{timeZone:'UTC'})+' UTC':'Never'}</small></>}{p.id==='github'&&!demo?<GitHubConnection companyId={companyId} connected={c?.status==='connected'} repository={typeof c?.metadata?.repository==='string'?c.metadata.repository:undefined} oauth={c?.connection_type==='oauth'}/>:p.available?<small>Available in the live workspace.</small>:<small>Coming next. No credentials are collected yet.</small>}</article>})}</div>
      {!data.connections.some(c=>c.provider==='github'&&c.connection_type==='oauth')&&<details className="v3-card"><summary>Use a public repository without signing in</summary><form className="v3-form" onSubmit={async e=>{e.preventDefault();await run({op:'connect',repository});}}><p>Fallback mode: imports a read-only snapshot of public issues.</p><label>Repository<input required value={repository} onChange={e=>setRepository(e.target.value)} placeholder="owner/repository" maxLength={150}/></label><button disabled={busy}>{busy?'Connecting…':'Connect public repository'}</button></form></details>}
      <h2>Planned connectors</h2><div className="v3-provider-grid">{CONNECTORS.filter(c=>!PROVIDERS.some(p=>p.id===c.id)).map(c=><article className="v3-card" key={c.id}><h3>{c.name}</h3><span className="v3-badge">Coming soon</span><p>Planned: {c.capabilities.join(", ")}. No executable integration yet.</p></article>)}</div><h2>Sync history</h2>{data.syncs.length?data.syncs.map(s=><article className="v3-card" key={s.id}><b>{s.status}</b><p>{s.error_message??'Issue snapshot imported; duplicates are ignored.'}</p><small>{new Date(s.created_at).toLocaleString('en-GB',{timeZone:'UTC'})+' UTC'}</small></article>):<p>No syncs yet.</p>}
    </>:section==='automations'?<>
      <article className="v3-card"><h2>Create follow-up tasks from insights</h2><p>When you refresh intelligence or sync GitHub, create one internal task for each new insight. Enabling this authorizes those low-risk task creations. It cannot deploy code or change external accounts.</p><p className="v3-notice">Runs on refresh/sync only. A background scheduler is not configured.</p><button className="v3-button" role="switch" aria-checked={automation?.enabled??false} disabled={busy} onClick={()=>run({op:'automation',enabled:!automation?.enabled})}>{automation?.enabled?'Enabled — turn off':'Disabled — enable'}</button><button className="v3-button" disabled={busy||!automation?.enabled} onClick={()=>run({op:'refresh'})}>Run now</button></article>
      <h2>Run history</h2>{data.runs.length?data.runs.map(r=><article className="v3-card" key={r.id}><b>{r.status}</b><small>{new Date(r.created_at).toLocaleString('en-GB',{timeZone:'UTC'})+' UTC'}</small><pre>{evidenceText(r)}</pre></article>):<p>No automation runs yet.</p>}
    </>:<>
      {section==='insights'&&<div className="v3-button-row"><button disabled={busy} className="v3-primary" onClick={()=>run({op:'refresh'})}>Refresh intelligence</button>{data.insights.some(i=>['resolved','dismissed'].includes(i.status??''))&&<button type="button" onClick={()=>setShowResolved(value=>!value)}>{showResolved?'Hide resolved history':'Show resolved history'}</button>}<small>Currently detects blocked and overdue internal tasks. Other anomaly detectors need connected outcome data.</small></div>}
      {section==='approvals'&&<form className="v3-card v3-form" onSubmit={async e=>{e.preventDefault();const key=requestKey||crypto.randomUUID();setRequestKey(key);if(await run({op:'propose',actionType,title,description,key,...(actionType==='github.create_pull_request'?{path:filePath,content:fileContent}:{})})){setTitle('');setDescription('');setFileContent('');setRequestKey('');}}}><h2>Prepare an approved action</h2><label>Action<select value={actionType} onChange={e=>setActionType(e.target.value)}><option value="create_task">Create task</option><option value="create_mission">Create mission</option><option value="record_decision">Record decision</option><option value="update_memory">Add company learning</option><option value="github.create_pull_request">Create GitHub pull request</option></select></label><label>Title<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Reason / description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={3000}/></label>{actionType==='github.create_pull_request'&&<><p className="v3-notice">Approval creates a branch, commits this exact file, and opens a pull request. It never merges or deploys.</p><label>Repository file path<input required value={filePath} onChange={e=>setFilePath(e.target.value)} maxLength={240}/></label><label>Complete file content<textarea required value={fileContent} onChange={e=>setFileContent(e.target.value)} maxLength={100000}/></label></>}<button disabled={busy||!!edit} className="v3-primary">Prepare for approval</button></form>}
      {!records.length&&<article className="v3-card v3-empty"><h2>Nothing here yet</h2><p>{section==='insights'?'Refresh intelligence to check current tasks. If nothing is flagged, no warnings are invented.':section==='investigations'?'Start an investigation from an insight.':section==='approvals'?'Actions you prepare appear here before anything is executed.':'Events and action results will appear as you use connected intelligence.'}</p></article>}
      {records.map(r=><article className="v3-card v3-record" key={r.id}>
        <div className="v3-card-heading"><span className="v3-badge">{r.status??r.source??'Observed'}{r.risk_level?` · ${r.risk_level} risk`:''}</span><small>{new Date(r.occurred_at??r.created_at).toLocaleString('en-GB',{timeZone:'UTC'})+' UTC'}</small></div><h2>{r.title}</h2>{isAgentId(r.agent_id)&&<p><b>{AGENTS[r.agent_id].name}</b> · {r.permission_level}</p>}<p>{r.description}</p>
        {r.hypothesis&&<p><b>Hypothesis, not proven:</b> {r.hypothesis}</p>}{r.conclusion&&<p>{r.conclusion}</p>}{r.recommended_action&&<p><b>Recommended next step:</b> {r.recommended_action}</p>}
        {section==='insights'&&r.confidence!=null&&<small>Detection certainty: {Math.round(r.confidence*100)}% for the recorded task state; not a probability of the cause.</small>}
        {r.evidence!=null&&<details><summary>View supporting evidence</summary><pre>{evidenceText(r.evidence)}</pre></details>}
        {r.error_message&&<p role="alert" className="v3-error">{r.error_message}</p>}{section==='executions'&&<><p>Tool: {r.provider} · Approval: {r.permission_level==='AUTO'?'Automatic internal analysis':r.approved_at?'Recorded':'Not approved'}</p><details><summary>Result / input</summary><pre>{evidenceText(r.output_payload)}{evidenceText(r.input_payload)}</pre></details></>}
        <small className="v3-record-id">Record {r.id}</small>
        {section==='insights'&&!['resolved','dismissed'].includes(r.status??'')&&<div className="v3-button-row"><button disabled={busy} onClick={async()=>{await run({op:'investigate',id:r.id});}}>Investigate</button><button disabled={busy} onClick={()=>run({op:'propose',id:r.id,source:'insight'})}>Prepare task</button><button disabled={busy} onClick={()=>run({op:'dismiss',id:r.id})}>Dismiss</button><Link href={href('investigations')}>View investigations →</Link></div>}
        {section==='investigations'&&r.status==='completed'&&<div className="v3-button-row"><button disabled={busy} onClick={()=>run({op:'propose',id:r.id,source:'investigation'})}>Prepare follow-up task</button><Link href={href('approvals')}>Review actions →</Link></div>}
        {section==='approvals'&&<><p>Impact: {r.action_type==='github.create_pull_request'?'Creates a GitHub branch, commit and pull request. It does not merge or deploy.':r.action_type==='update_task'?'Changes the selected internal task state.':'Saves an internal company record. No external code, billing or customer messages will change.'}</p>{r.action_type==='github.create_pull_request'&&<details><summary>Review exact GitHub change</summary><pre>{evidenceText(r.input_payload)}</pre></details>}<div className="v3-button-row"><button className="v3-primary" disabled={busy} onClick={()=>run({op:'approve',id:r.id})}>{demo?'Simulate approval':'Approve & execute'}</button><button disabled={busy||r.action_type==='github.create_pull_request'} onClick={()=>{setEdit(r);setTitle(r.title??'');setDescription(r.description??'');}}>Modify</button><button disabled={busy} onClick={()=>run({op:'reject',id:r.id})}>Reject</button></div></>}
      </article>)}
      {edit&&<form className="v3-card v3-form" onSubmit={async e=>{e.preventDefault();if(await run({op:'modify',id:edit.id,title,description})){setEdit(null);setTitle('');setDescription('');}}}><h2>Modify pending action</h2><label>Title<input required value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><button disabled={busy}>Save changes</button><button type="button" onClick={()=>{setEdit(null);setTitle('');setDescription('');}}>Cancel</button></form>}
    </>}
  </section>;
}
