"use client";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useEffect, useState } from "react";
import ThemeToggle from "../../components/theme-toggle";
const agents = ["Market intelligence", "Customer reality", "Competitive terrain", "Business model", "Risk review", "MVP & execution"];
export default function Workspace() { return <Suspense fallback={<main className="app-shell"/>}><WorkspaceContent/></Suspense>; }
const INTAKE_KEY = "cofounder-intake";
function WorkspaceContent() { const router = useRouter(); const params = useSearchParams(); const [active, setActive] = useState(0); const [result, setResult] = useState<{ id?: string; error?: string; warning?: string; saved?: boolean } | null>(null); const idea = params.get("idea") || "Your new business idea"; useEffect(() => { const timer = setInterval(() => setActive(x => x >= 5 ? 5 : x + 1), 760); let payload: Record<string, string> = { idea }; try { const stored = sessionStorage.getItem(INTAKE_KEY); if (stored) { const parsed = JSON.parse(stored); if (parsed?.idea === idea) payload = parsed; } } catch { /* sessionStorage unavailable */ } fetch("/api/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }).then(async response => { let data: { id?: string; error?: string; warning?: string; saved?: boolean } | null = null; try { data = await response.json(); } catch { /* non-JSON error body */ } if (!response.ok) { setResult({ error: data?.error || "The request failed. Try again." }); return; } setResult(data); try { sessionStorage.removeItem(INTAKE_KEY); } catch { /* ignore */ } }).catch(() => setResult({ error: "Could not reach the server. Check your connection and try again." })); return () => clearInterval(timer); }, [idea]); return <main className="app-shell">
<header className="app-nav"><a className="brand" href="/"><img src="/logo-mark.png" alt="" className="brand-mark" /> AI Co-Founder</a><div><a href="/reports">My reports</a><a href="/pricing">Pricing</a><ThemeToggle/></div></header><section className="workspace"><aside className="workspace-side"><p>YOUR IDEA</p><h2>{idea}</h2><span className="side-status">● Research in progress</span><hr/><small>YOUR TEAM</small>{agents.slice(0,3).map((agent,index)=><div className="person" key={agent}><i className={`person-dot dot-${index}`}></i><span>{agent}</span></div>)}</aside><div className="research-panel"><div className="eyebrow"><span></span> CO-FOUNDER SESSION</div><h1>We&rsquo;re challenging<br/>the opportunity.</h1><p>Each specialist is looking for evidence, assumptions and the questions that can change your decision.</p><div className="run-list">{agents.map((agent,index)=><div className={index <= active ? "run active" : "run"} key={agent}><span>{index < active ? "✓" : String(index + 1).padStart(2,"0")}</span><div><b>{agent}</b><small>{index < active ? "Insight ready" : index === active ? "Investigating the opportunity…" : "Waiting for the room"}</small></div><i>{index < active ? "Complete" : index === active ? "Working" : "Queued"}</i></div>)}</div>
{active === 5 && (
  result?.id ? <button className="primary-action" onClick={() => router.push(`/report/${result.id}`)}>Open my decision brief →</button>
  : result?.error ? <div className="workspace-notice"><p>{result.error}</p><button className="primary-action" onClick={() => location.reload()}>Try again</button></div>
  : result && !result.saved ? <div className="workspace-notice"><p>{result.warning || "This report was generated but couldn't be saved without an account."} Sign in and generate again to keep and view your report.</p><a className="primary-action" href="/auth">Sign in →</a></div>
  : <p className="side-status">Finishing up…</p>
)}
</div></section></main>; }
