"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useEffect, useState } from "react";
const stages = ["CEO reads your founder brief", "Research Agent gathers live sources", "CEO separates evidence from assumptions", "CEO chooses the required specialists", "CEO prepares your business report"];
export default function Workspace() { return <Suspense fallback={<main className="app-shell"/>}><WorkspaceContent/></Suspense>; }
const INTAKE_KEY = "cofounder-intake";
function WorkspaceContent() { const router = useRouter(); const params = useSearchParams(); const [active, setActive] = useState(0); const [result, setResult] = useState<{ id?: string; error?: string; warning?: string; saved?: boolean; ceoPlan?: { selectedAgents?: { agentId: string }[] } } | null>(null); const idea = params.get("idea") || "Your new business idea"; useEffect(() => { const timer = setInterval(() => setActive(x => x >= stages.length ? stages.length : x + 1), 900); let payload: Record<string, string> = { idea }; try { const stored = sessionStorage.getItem(INTAKE_KEY); if (stored) { const parsed = JSON.parse(stored); if (parsed?.idea === idea) payload = parsed; } } catch { /* sessionStorage unavailable */ } fetch("/api/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }).then(async response => { let data: { id?: string; error?: string; warning?: string; saved?: boolean; ceoPlan?: { selectedAgents?: { agentId: string }[] } } | null = null; try { data = await response.json(); } catch { /* non-JSON error body */ } if (!response.ok) { setResult({ error: data?.error || "The request failed. Try again." }); return; } setResult(data); try { sessionStorage.removeItem(INTAKE_KEY); } catch { /* ignore */ } }).catch(() => setResult({ error: "Could not reach the server. Check your connection and try again." })); return () => clearInterval(timer); }, [idea]); const selected=result?.ceoPlan?.selectedAgents?.map(agent=>`${agent.agentId[0].toUpperCase()}${agent.agentId.slice(1)} Agent`)??[]; return <main className="app-shell">
<header className="app-nav"><Link className="brand" href="/"><img src="/logo-mark.png" alt="" className="brand-mark" /> AI Co-Founder</Link><div><Link href="/reports">My reports</Link><Link href="/pricing">Pricing</Link></div></header><section className="workspace"><aside className="workspace-side"><p>YOUR IDEA</p><h2>{idea}</h2><span className="side-status">● CEO analysis in progress</span><hr/><small>YOUR LEAD</small><div className="person"><i className="person-dot dot-0"></i><span>CEO Agent</span></div><div className="person"><i className="person-dot dot-1"></i><span>Research Agent</span></div>{selected.length>0&&<><hr/><small>CEO SELECTED</small>{selected.map((agent,index)=><div className="person" key={agent}><i className={`person-dot dot-${index+1}`}></i><span>{agent}</span></div>)}</>}</aside><div className="research-panel"><div className="eyebrow"><span></span> CEO AGENT SESSION</div><h1>Your CEO is turning<br/>the idea into a decision.</h1><p>The CEO gathers evidence, identifies what kind of business this is, and assigns only the specialists the company needs.</p><div className="run-list">{stages.map((stage,index)=><div className={index <= active ? "run active" : "run"} key={stage}><span>{index < active ? "✓" : String(index + 1).padStart(2,"0")}</span><div><b>{stage}</b><small>{index < active ? "Complete" : index === active ? "Working with your brief…" : "Waiting"}</small></div><i>{index < active ? "Complete" : index === active ? "Working" : "Queued"}</i></div>)}</div>
{active === stages.length && (
  result?.id ? <button className="primary-action" onClick={() => router.push(`/report/${result.id}`)}>Open CEO report and agent plan →</button>
  : result?.error ? <div className="workspace-notice"><p>{result.error}</p><button className="primary-action" onClick={() => location.reload()}>Try again</button></div>
  : result && !result.saved ? <div className="workspace-notice"><p>{result.warning || "This report was generated but couldn't be saved without an account."} Sign in and generate again to keep and view your report.</p><a className="primary-action" href="/auth">Sign in →</a></div>
  : <p className="side-status">Finishing up…</p>
)}
</div></section></main>; }
